/* ═══════════════════════════════════════════
   MOCK DATA — AceIntel
   ═══════════════════════════════════════════ */

const PLAYERS_DB = {
  "Anna Blinkova": {
    name: "Anna Blinkova",
    country: "Russia 🇷🇺",
    rank: 21,
    age: 25,
    hand: "Right",
    surfaces: {
      grass: { winPct: 62, rating: 78, strength: "Strong" },
      clay:  { winPct: 55, rating: 70, strength: "Average" },
      hard:  { winPct: 68, rating: 84, strength: "Elite" },
    },
    stats: {
      serve:    82,
      return:   76,
      elo:      1845,
      pressure: 71,
      tiebreak: 64,
      breakPt:  48,
    },
    form: "Hot",
    recentMatches: [
      { opponent: "Iga Świątek",      event: "Roland Garros R4",   score: "6-3 4-6 7-5", result: "win" },
      { opponent: "Coco Gauff",       event: "Rome QF",            score: "7-6 6-4",      result: "win" },
      { opponent: "Jessica Pegula",   event: "Rome R3",            score: "6-2 6-3",      result: "win" },
      { opponent: "Elena Rybakina",   event: "Madrid SF",          score: "3-6 6-7",      result: "loss" },
      { opponent: "Aryna Sabalenka",  event: "Madrid QF",          score: "6-4 7-5",      result: "win" },
      { opponent: "Beatriz Haddad",   event: "Stuttgart R2",       score: "6-1 6-4",      result: "win" },
      { opponent: "Maria Sakkari",    event: "Indian Wells R4",    score: "4-6 3-6",      result: "loss" },
      { opponent: "Daria Kasatkina",  event: "Indian Wells R3",    score: "7-5 6-2",      result: "win" },
      { opponent: "Caroline Garcia",  event: "Dubai QF",           score: "6-3 6-4",      result: "win" },
      { opponent: "Karolina Muchova", event: "Dubai R3",           score: "7-6 4-6 6-3",  result: "win" },
    ],
    h2h: {
      opponent: "Iga Świątek",
      opponentRank: 1,
      record: "3 - 5",
      stats: {
        "Aces/Match":       { p1: 4.2,  p2: 3.1 },
        "1st Serve %":      { p1: 67,   p2: 71 },
        "Break Points Won": { p1: 42,   p2: 48 },
        "Winners":          { p1: 28,   p2: 32 },
        "Unforced Errors":  { p1: 22,   p2: 19 },
        "Net Points Won":   { p1: 65,   p2: 58 },
      },
    },
    aiInsights: {
      summary: "Anna Blinkova is enjoying a career-best season with a strong surge up the rankings. Her aggressive baseline game has become more consistent, and her improved first serve has been a game-changer on hard courts. She has shown the ability to compete with top-5 players and regularly reaches the latter stages of Premier events.",
      strengths: [
        "Powerful first serve that regularly exceeds 180 km/h",
        "Aggressive return game that puts opponents under immediate pressure",
        "Exceptional hard-court movement and court coverage",
        "Strong mental resilience in tight sets — wins 71% of deciding sets",
      ],
      weaknesses: [
        "Inconsistent on clay, especially in long rallies",
        "Second serve can become vulnerable under pressure",
        "Net game remains a work in progress",
        "Tiebreak record below tour average",
      ],
      tags: ["Power Baseline", "Hard Court Specialist", "Rising Star", "Strong Serve", "Clutch Performer"],
    },
  },

  "Carlos Alcaraz": {
    name: "Carlos Alcaraz",
    country: "Spain 🇪🇸",
    rank: 2,
    age: 23,
    hand: "Right",
    surfaces: {
      grass: { winPct: 82, rating: 93, strength: "Elite" },
      clay:  { winPct: 85, rating: 95, strength: "Elite" },
      hard:  { winPct: 80, rating: 91, strength: "Elite" },
    },
    stats: {
      serve:    91,
      return:   88,
      elo:      2150,
      pressure: 89,
      tiebreak: 78,
      breakPt:  56,
    },
    form: "On Fire",
    recentMatches: [
      { opponent: "Jannik Sinner",    event: "Roland Garros F",    score: "6-3 2-6 6-3 6-4", result: "win" },
      { opponent: "Alexander Zverev", event: "Roland Garros SF",   score: "6-4 7-5 6-2",     result: "win" },
      { opponent: "Stefanos Tsitsipas",event:"Roland Garros QF",   score: "6-2 6-3 6-4",     result: "win" },
      { opponent: "Felix Auger-A.",   event: "Rome F",             score: "7-5 6-3",         result: "win" },
      { opponent: "Daniil Medvedev",  event: "Rome SF",            score: "6-4 6-7 7-6",     result: "win" },
      { opponent: "Holger Rune",      event: "Madrid F",           score: "6-1 6-4",         result: "win" },
      { opponent: "Novak Djokovic",   event: "Madrid SF",          score: "3-6 7-6 6-4",     result: "win" },
      { opponent: "Andrey Rublev",    event: "Madrid QF",          score: "6-3 6-4",         result: "win" },
      { opponent: "Taylor Fritz",     event: "Indian Wells F",     score: "4-6 3-6",         result: "loss" },
      { opponent: "Ben Shelton",      event: "Indian Wells SF",    score: "7-6 6-4",         result: "win" },
    ],
    h2h: {
      opponent: "Jannik Sinner",
      opponentRank: 1,
      record: "6 - 4",
      stats: {
        "Aces/Match":       { p1: 8.4,  p2: 7.2 },
        "1st Serve %":      { p1: 69,   p2: 72 },
        "Break Points Won": { p1: 45,   p2: 41 },
        "Winners":          { p1: 38,   p2: 34 },
        "Unforced Errors":  { p1: 28,   p2: 21 },
        "Net Points Won":   { p1: 72,   p2: 61 },
      },
    },
    aiInsights: {
      summary: "Carlos Alcaraz continues to operate at an otherworldly level, dominating across all surfaces. His combination of raw power, supernatural court coverage, and drop-shot artistry make him the most complete player on tour. His 2026 clay swing has been virtually flawless, and he enters the grass season as the overwhelming favorite for Wimbledon.",
      strengths: [
        "All-surface dominance — elite ratings on grass, clay, and hard",
        "Drop-shot artistry that disrupts opponent rhythm",
        "Extraordinary court coverage for his power level",
        "Mental fortitude in Grand Slam situations — 89% pressure rating",
      ],
      weaknesses: [
        "Occasional lapses in concentration during second sets",
        "Higher unforced error count compared to Sinner",
        "Tendency to go for too much on second serve returns",
        "Fitness management in best-of-5 marathons",
      ],
      tags: ["Complete Player", "All-Surface King", "Drop Shot Artist", "Grand Slam Champion", "Generational Talent"],
    },
  },

  "Iga Swiatek": {
    name: "Iga Świątek",
    country: "Poland 🇵🇱",
    rank: 1,
    age: 25,
    hand: "Right",
    surfaces: {
      grass: { winPct: 68, rating: 76, strength: "Strong" },
      clay:  { winPct: 92, rating: 98, strength: "Elite" },
      hard:  { winPct: 78, rating: 87, strength: "Elite" },
    },
    stats: {
      serve:    84,
      return:   92,
      elo:      2210,
      pressure: 86,
      tiebreak: 72,
      breakPt:  58,
    },
    form: "Dominant",
    recentMatches: [
      { opponent: "Aryna Sabalenka",  event: "Roland Garros F",    score: "6-2 6-1",         result: "win" },
      { opponent: "Coco Gauff",       event: "Roland Garros SF",   score: "6-3 6-4",         result: "win" },
      { opponent: "Anna Blinkova",    event: "Roland Garros QF",   score: "6-4 7-5",         result: "win" },
      { opponent: "Elena Rybakina",   event: "Rome F",             score: "6-0 6-3",         result: "win" },
      { opponent: "Jessica Pegula",   event: "Rome SF",            score: "6-2 6-2",         result: "win" },
      { opponent: "Marketa Vondrousova",event:"Madrid F",          score: "6-3 6-1",         result: "win" },
      { opponent: "Aryna Sabalenka",  event: "Madrid SF",          score: "7-5 6-4",         result: "win" },
      { opponent: "Coco Gauff",       event: "Indian Wells F",     score: "3-6 6-4 6-7",     result: "loss" },
      { opponent: "Elena Rybakina",   event: "Indian Wells SF",    score: "6-3 7-6",         result: "win" },
      { opponent: "Maria Sakkari",    event: "Dubai F",            score: "6-1 6-3",         result: "win" },
    ],
    h2h: {
      opponent: "Aryna Sabalenka",
      opponentRank: 2,
      record: "7 - 3",
      stats: {
        "Aces/Match":       { p1: 2.8,  p2: 5.6 },
        "1st Serve %":      { p1: 71,   p2: 65 },
        "Break Points Won": { p1: 52,   p2: 40 },
        "Winners":          { p1: 30,   p2: 36 },
        "Unforced Errors":  { p1: 16,   p2: 26 },
        "Net Points Won":   { p1: 55,   p2: 62 },
      },
    },
    aiInsights: {
      summary: "Iga Świątek remains the undisputed queen of clay and has continued to solidify her all-surface credentials. Her 2026 clay season has been historically dominant, dropping fewer than 15 games in her last four clay finals combined. The return game remains the best in women's tennis, and her mental composure in big moments has reached elite levels.",
      strengths: [
        "Best return game in WTA — 92 rating, breaks serve at will",
        "Clay court dominance approaching Nadal-like levels",
        "Remarkably low unforced error count — exceptional discipline",
        "High pressure performance — thrives in Grand Slam environments",
      ],
      weaknesses: [
        "Grass remains relatively weaker surface despite improvements",
        "Lower ace count limits free points on serve",
        "Can struggle against heavy-serving opponents in fast conditions",
        "Tiebreak conversion rate below what's expected for #1 player",
      ],
      tags: ["Clay Court Queen", "Return Specialist", "Grand Slam Dominant", "Consistent Machine", "Mentally Elite"],
    },
  },

  "Jannik Sinner": {
    name: "Jannik Sinner",
    country: "Italy 🇮🇹",
    rank: 1,
    age: 24,
    hand: "Right",
    surfaces: {
      grass: { winPct: 78, rating: 88, strength: "Elite" },
      clay:  { winPct: 75, rating: 83, strength: "Strong" },
      hard:  { winPct: 88, rating: 96, strength: "Elite" },
    },
    stats: {
      serve:    89,
      return:   90,
      elo:      2190,
      pressure: 92,
      tiebreak: 82,
      breakPt:  54,
    },
    form: "Dominant",
    recentMatches: [
      { opponent: "Carlos Alcaraz",   event: "Roland Garros F",    score: "3-6 6-2 3-6 4-6", result: "loss" },
      { opponent: "Daniil Medvedev",  event: "Roland Garros SF",   score: "6-2 6-4 7-5",     result: "win" },
      { opponent: "Alexander Zverev", event: "Roland Garros QF",   score: "6-3 7-6 6-4",     result: "win" },
      { opponent: "Taylor Fritz",     event: "Rome SF",            score: "6-4 6-3",         result: "win" },
      { opponent: "Holger Rune",      event: "Rome QF",            score: "6-1 7-5",         result: "win" },
      { opponent: "Novak Djokovic",   event: "Madrid QF",          score: "7-6 6-4",         result: "win" },
      { opponent: "Stefanos Tsitsipas",event:"Miami F",            score: "6-3 6-2",         result: "win" },
      { opponent: "Andrey Rublev",    event: "Indian Wells F",     score: "6-1 6-2",         result: "win" },
      { opponent: "Ben Shelton",      event: "Indian Wells SF",    score: "7-5 6-3",         result: "win" },
      { opponent: "Alex de Minaur",   event: "Australian Open F",  score: "6-3 6-4 6-2",     result: "win" },
    ],
    h2h: {
      opponent: "Carlos Alcaraz",
      opponentRank: 2,
      record: "4 - 6",
      stats: {
        "Aces/Match":       { p1: 7.2,  p2: 8.4 },
        "1st Serve %":      { p1: 72,   p2: 69 },
        "Break Points Won": { p1: 41,   p2: 45 },
        "Winners":          { p1: 34,   p2: 38 },
        "Unforced Errors":  { p1: 21,   p2: 28 },
        "Net Points Won":   { p1: 61,   p2: 72 },
      },
    },
    aiInsights: {
      summary: "Jannik Sinner is the current world #1 and arguably the most consistent player on tour. His 2026 hard-court season was historically dominant, winning the Australian Open, Indian Wells, and Miami without dropping a set. His ball-striking precision and tactical intelligence continue to set new standards, though Alcaraz remains his kryptonite in best-of-5 encounters.",
      strengths: [
        "Hard court mastery — 96 rating with 88% win rate",
        "Highest pressure performance rating on tour (92)",
        "Remarkably clean ball-striking — fewest unforced errors among top 5",
        "Dominant tiebreak record reflects elite clutch ability",
      ],
      weaknesses: [
        "Head-to-head deficit against Alcaraz, especially on clay",
        "Clay court game still a tier below the very best",
        "Can become passive in rallies against aggressive opponents",
        "Net game has improved but still not a reliable weapon",
      ],
      tags: ["World #1", "Hard Court King", "Precision Machine", "Clutch Master", "Tactical Genius"],
    },
  },
};

// Trending players
const TRENDING_PLAYERS = [
  {
    name: "Carlos Alcaraz",
    country: "Spain 🇪🇸",
    rank: 2,
    surface: "All Courts",
    form: "On Fire",
    formColor: "green",
  },
  {
    name: "Iga Świątek",
    country: "Poland 🇵🇱",
    rank: 1,
    surface: "Clay",
    form: "Dominant",
    formColor: "green",
  },
  {
    name: "Jannik Sinner",
    country: "Italy 🇮🇹",
    rank: 1,
    surface: "Hard Court",
    form: "Dominant",
    formColor: "green",
  },
  {
    name: "Anna Blinkova",
    country: "Russia 🇷🇺",
    rank: 21,
    surface: "Hard Court",
    form: "Hot",
    formColor: "amber",
  },
  {
    name: "Coco Gauff",
    country: "USA 🇺🇸",
    rank: 3,
    surface: "Hard Court",
    form: "Steady",
    formColor: "cyan",
  },
  {
    name: "Novak Djokovic",
    country: "Serbia 🇷🇸",
    rank: 5,
    surface: "All Courts",
    form: "Rebuilding",
    formColor: "amber",
  },
  {
    name: "Elena Rybakina",
    country: "Kazakhstan 🇰🇿",
    rank: 4,
    surface: "Grass",
    form: "Strong",
    formColor: "green",
  },
  {
    name: "Alexander Zverev",
    country: "Germany 🇩🇪",
    rank: 3,
    surface: "Clay",
    form: "Inconsistent",
    formColor: "amber",
  },
];
