/* ═══════════════════════════════════════════
   DEEP PLAYER PROFILE DATA — AceIntel
   ═══════════════════════════════════════════ */

const PROFILE_DB = {

  "Anna Blinkova": {
    // ─── Overview ────────────────────────
    overview: {
      name: "Anna Blinkova",
      age: 25,
      nationality: "Russia",
      flag: "🇷🇺",
      handedness: "Right-Handed",
      backhand: "Two-Handed",
      height: "5'9\" (175 cm)",
      coach: "Alexei Zhuk",
      currentRank: 21,
      peakRank: 14,
      elo: 1845,
      recentForm: ["W","W","W","L","W","W","L","W","W","W"],
      careerWinLoss: "287-198",
      careerWinPct: 59.2,
      ytdWinLoss: "38-12",
      ytdWinPct: 76.0,
      prizeMoney: "$4,280,000",
      titlesTotal: 5,
    },

    // ─── Surface Intelligence ────────────
    surfaces: {
      grass: {
        winPct: 62,
        holdPct: 78,
        breakPct: 32,
        serveRating: 76,
        returnRating: 68,
        tiebreakRecord: "8-6",
        last52: { wins: 18, losses: 11, winPct: 62 },
        strength: "Strong",
      },
      clay: {
        winPct: 55,
        holdPct: 72,
        breakPct: 36,
        serveRating: 68,
        returnRating: 72,
        tiebreakRecord: "5-8",
        last52: { wins: 22, losses: 18, winPct: 55 },
        strength: "Average",
      },
      hard: {
        winPct: 68,
        holdPct: 84,
        breakPct: 40,
        serveRating: 85,
        returnRating: 78,
        tiebreakRecord: "12-7",
        last52: { wins: 41, losses: 19, winPct: 68 },
        strength: "Elite",
      },
      indoor: {
        winPct: 71,
        holdPct: 86,
        breakPct: 38,
        serveRating: 83,
        returnRating: 74,
        tiebreakRecord: "6-4",
        last52: { wins: 15, losses: 6, winPct: 71 },
        strength: "Strong",
      },
    },
    bestSurface: "Hard Court",

    // ─── Recent Matches ─────────────────
    recentMatches: [
      { opponent: "Iga Świątek",       surface: "Clay",  result: "win",  score: "6-3 4-6 7-5", tournament: "Roland Garros R4",  date: "Jun 2, 2026" },
      { opponent: "Coco Gauff",        surface: "Clay",  result: "win",  score: "7-6 6-4",      tournament: "Rome QF",           date: "May 18, 2026" },
      { opponent: "Jessica Pegula",    surface: "Clay",  result: "win",  score: "6-2 6-3",      tournament: "Rome R3",           date: "May 16, 2026" },
      { opponent: "Elena Rybakina",    surface: "Clay",  result: "loss", score: "3-6 6-7",      tournament: "Madrid SF",         date: "May 8, 2026" },
      { opponent: "Aryna Sabalenka",   surface: "Clay",  result: "win",  score: "6-4 7-5",      tournament: "Madrid QF",         date: "May 6, 2026" },
      { opponent: "Beatriz Haddad",    surface: "Clay",  result: "win",  score: "6-1 6-4",      tournament: "Stuttgart R2",      date: "Apr 22, 2026" },
      { opponent: "Maria Sakkari",     surface: "Hard",  result: "loss", score: "4-6 3-6",      tournament: "Indian Wells R4",   date: "Mar 14, 2026" },
      { opponent: "Daria Kasatkina",   surface: "Hard",  result: "win",  score: "7-5 6-2",      tournament: "Indian Wells R3",   date: "Mar 12, 2026" },
      { opponent: "Caroline Garcia",   surface: "Hard",  result: "win",  score: "6-3 6-4",      tournament: "Dubai QF",          date: "Feb 22, 2026" },
      { opponent: "Karolina Muchova",  surface: "Hard",  result: "win",  score: "7-6 4-6 6-3",  tournament: "Dubai R3",          date: "Feb 20, 2026" },
    ],

    // ─── Serve Analytics ────────────────
    serve: {
      firstServePct:    { value: 62, tourAvg: 60, explanation: "How often her first serve goes in. Slightly above average — she takes risks for power." },
      firstServeWonPct: { value: 71, tourAvg: 65, explanation: "Points won when the first serve lands. Strong — her power pays off when accurate." },
      secondServeWonPct:{ value: 48, tourAvg: 50, explanation: "Points won on second serve. Slightly below average — opponents attack her second serve." },
      acesPct:          { value: 8.2, tourAvg: 5.0, explanation: "Percentage of service points that are aces. Well above average — a genuine weapon." },
      doubleFaultsPct:  { value: 4.8, tourAvg: 4.5, explanation: "Percentage of service points that are double faults. Marginally above average — the cost of aggression." },
      breakPointsSavedPct: { value: 62, tourAvg: 60, explanation: "Break points saved. Solid — she doesn't panic under pressure on serve." },
    },

    // ─── Return Analytics ────────────────
    returnAnalytics: {
      returnPointsWon:  { value: 42, tourAvg: 40, explanation: "Total return points won. Above average — her aggressive returns create pressure." },
      breakConversion:  { value: 44, tourAvg: 42, explanation: "Break points converted into breaks. Slightly above average — efficient when she earns chances." },
      returnGamesWon:   { value: 28, tourAvg: 25, explanation: "Percentage of return games won (broke the opponent). Strong — she's dangerous on return." },
    },

    // ─── Strength Meter ─────────────────
    strengthMeter: {
      serve:              82,
      return:             76,
      consistency:        68,
      pressurePoints:     71,
      surfaceAdaptability:64,
    },

    // ─── AI Summary ─────────────────────
    aiSummary: "Anna Blinkova is strongest on hard courts where her powerful serve and aggressive returning dominate. She struggles on clay in long baseline rallies, and her grass game is hampered by opponents who serve aggressively. On hard courts, she wins 68% of matches and ranks among the top 20 returners on the tour. Her serve — clocking above 180 km/h — is her biggest weapon, but her second serve remains a vulnerability that top opponents exploit. In pressure moments, she holds firm (71 pressure rating), though her tiebreak record is inconsistent. Overall, she's a rising force best suited to fast surfaces.",

    // ─── Prediction Engine Data ─────────
    predictions: {
      "Iga Swiatek":      { winChance: 28, confidence: "Medium",   surface: "Hard", reasoning: "Blinkova's serve power gives her chances, but Świątek's return dominance (92 rating) neutralizes most servers. On clay, Blinkova's odds drop to ~18%." },
      "Carlos Alcaraz":   { winChance: 12, confidence: "High",     surface: "Hard", reasoning: "Alcaraz is elite across every metric. Blinkova's best chance is on a fast hard court where her serve can create free points." },
      "Jannik Sinner":    { winChance: 15, confidence: "High",     surface: "Hard", reasoning: "Sinner's consistency and pressure performance (92) are overwhelming. Blinkova's aggression could snag a set but unlikely to win a match." },
      "Coco Gauff":       { winChance: 45, confidence: "Medium",   surface: "Hard", reasoning: "Close matchup. Blinkova's serve is stronger, but Gauff's return game is excellent. Recent results favor Blinkova." },
      "Elena Rybakina":   { winChance: 38, confidence: "Medium",   surface: "Hard", reasoning: "Two power servers — rallies will be short. Whoever serves better on the day likely wins. Rybakina edges it on grass." },
      "Aryna Sabalenka":  { winChance: 35, confidence: "Medium",   surface: "Hard", reasoning: "Sabalenka's power matches Blinkova's, but she's more experienced in big moments. Blinkova has won their last meeting." },
    },
  },

  "Carlos Alcaraz": {
    overview: {
      name: "Carlos Alcaraz",
      age: 23,
      nationality: "Spain",
      flag: "🇪🇸",
      handedness: "Right-Handed",
      backhand: "Two-Handed",
      height: "6'1\" (185 cm)",
      coach: "Juan Carlos Ferrero",
      currentRank: 2,
      peakRank: 1,
      elo: 2150,
      recentForm: ["W","W","W","W","W","W","W","W","L","W"],
      careerWinLoss: "248-52",
      careerWinPct: 82.7,
      ytdWinLoss: "46-5",
      ytdWinPct: 90.2,
      prizeMoney: "$38,500,000",
      titlesTotal: 19,
    },
    surfaces: {
      grass: {
        winPct: 82, holdPct: 91, breakPct: 42, serveRating: 90, returnRating: 86,
        tiebreakRecord: "14-4", last52: { wins: 18, losses: 4, winPct: 82 }, strength: "Elite",
      },
      clay: {
        winPct: 85, holdPct: 89, breakPct: 48, serveRating: 86, returnRating: 90,
        tiebreakRecord: "10-3", last52: { wins: 34, losses: 6, winPct: 85 }, strength: "Elite",
      },
      hard: {
        winPct: 80, holdPct: 88, breakPct: 40, serveRating: 89, returnRating: 84,
        tiebreakRecord: "18-6", last52: { wins: 44, losses: 11, winPct: 80 }, strength: "Elite",
      },
      indoor: {
        winPct: 78, holdPct: 87, breakPct: 38, serveRating: 88, returnRating: 82,
        tiebreakRecord: "8-3", last52: { wins: 14, losses: 4, winPct: 78 }, strength: "Elite",
      },
    },
    bestSurface: "Clay",
    recentMatches: [
      { opponent: "Jannik Sinner",      surface: "Clay",  result: "win",  score: "6-3 2-6 6-3 6-4", tournament: "Roland Garros F",    date: "Jun 8, 2026" },
      { opponent: "Alexander Zverev",   surface: "Clay",  result: "win",  score: "6-4 7-5 6-2",     tournament: "Roland Garros SF",   date: "Jun 6, 2026" },
      { opponent: "Stefanos Tsitsipas", surface: "Clay",  result: "win",  score: "6-2 6-3 6-4",     tournament: "Roland Garros QF",   date: "Jun 4, 2026" },
      { opponent: "Felix Auger-A.",     surface: "Clay",  result: "win",  score: "7-5 6-3",         tournament: "Rome F",             date: "May 19, 2026" },
      { opponent: "Daniil Medvedev",    surface: "Clay",  result: "win",  score: "6-4 6-7 7-6",     tournament: "Rome SF",            date: "May 17, 2026" },
      { opponent: "Holger Rune",        surface: "Clay",  result: "win",  score: "6-1 6-4",         tournament: "Madrid F",           date: "May 11, 2026" },
      { opponent: "Novak Djokovic",     surface: "Clay",  result: "win",  score: "3-6 7-6 6-4",     tournament: "Madrid SF",          date: "May 9, 2026" },
      { opponent: "Andrey Rublev",      surface: "Clay",  result: "win",  score: "6-3 6-4",         tournament: "Madrid QF",          date: "May 7, 2026" },
      { opponent: "Taylor Fritz",       surface: "Hard",  result: "loss", score: "4-6 3-6",         tournament: "Indian Wells F",     date: "Mar 16, 2026" },
      { opponent: "Ben Shelton",        surface: "Hard",  result: "win",  score: "7-6 6-4",         tournament: "Indian Wells SF",    date: "Mar 14, 2026" },
    ],
    serve: {
      firstServePct:        { value: 68, tourAvg: 62, explanation: "Excellent first-serve consistency. He rarely misses, giving him a huge platform to dominate." },
      firstServeWonPct:     { value: 78, tourAvg: 70, explanation: "Points won when the first serve lands. Elite — his variety of serves keeps opponents guessing." },
      secondServeWonPct:    { value: 56, tourAvg: 50, explanation: "Excellent second serve that generates genuine offense. Not easy to attack." },
      acesPct:              { value: 10.5, tourAvg: 7.0, explanation: "Strong ace rate. He can serve his way out of trouble in tight moments." },
      doubleFaultsPct:      { value: 3.8, tourAvg: 4.5, explanation: "Very controlled. Lower than tour average — he manages risk exceptionally." },
      breakPointsSavedPct:  { value: 68, tourAvg: 60, explanation: "Elite under pressure on serve. His clutch serving in tiebreaks is legendary." },
    },
    returnAnalytics: {
      returnPointsWon: { value: 44, tourAvg: 38, explanation: "Elite return performance. He neutralizes big servers with aggressive positioning." },
      breakConversion:  { value: 46, tourAvg: 40, explanation: "When he earns a break point, he converts at an exceptional rate." },
      returnGamesWon:   { value: 32, tourAvg: 24, explanation: "Breaks serve more than almost anyone on tour. A terror for servers." },
    },
    strengthMeter: { serve: 91, return: 88, consistency: 82, pressurePoints: 89, surfaceAdaptability: 95 },
    aiSummary: "Carlos Alcaraz is the most complete player in men's tennis. He dominates on every surface — his clay-court game is Nadal-esque, his grass game is Federer-like, and his hard court power rivals Djokovic's prime. His drop shots are the best in the sport's history, and his court coverage at his power level is unprecedented. The only weakness is occasional lapses in focus during middle sets, but his ability to raise his level in critical moments (89 pressure rating) makes him nearly unbeatable. He's the overwhelming favorite for every tournament he enters.",
    predictions: {
      "Jannik Sinner":    { winChance: 62, confidence: "High",   surface: "Clay", reasoning: "Alcaraz leads 6-4 in H2H and is especially dominant on clay. His variety disrupts Sinner's rhythm." },
      "Iga Swiatek":      { winChance: 95, confidence: "High",   surface: "Any",  reasoning: "Cross-gender comparison not applicable, but Alcaraz's metrics dominate every category." },
      "Anna Blinkova":    { winChance: 88, confidence: "High",   surface: "Hard", reasoning: "Massive quality gap. Alcaraz's all-around game overwhelms Blinkova's serve-dependent style." },
      "Novak Djokovic":   { winChance: 65, confidence: "Medium", surface: "Clay", reasoning: "Alcaraz has won 4 of last 5 meetings. Djokovic's declining movement is exploited by Alcaraz's drop shots." },
      "Alexander Zverev": { winChance: 72, confidence: "High",   surface: "Any",  reasoning: "Alcaraz dominates this matchup. Zverev's serve is his only weapon, and Alcaraz returns it too well." },
      "Daniil Medvedev":  { winChance: 68, confidence: "Medium", surface: "Hard", reasoning: "Medvedev's defense is world-class, but Alcaraz's power and variety eventually break through." },
    },
  },

  "Iga Swiatek": {
    overview: {
      name: "Iga Świątek",
      age: 25,
      nationality: "Poland",
      flag: "🇵🇱",
      handedness: "Right-Handed",
      backhand: "Two-Handed",
      height: "5'9\" (175 cm)",
      coach: "Tomasz Wiktorowski",
      currentRank: 1,
      peakRank: 1,
      elo: 2210,
      recentForm: ["W","W","W","W","W","W","W","L","W","W"],
      careerWinLoss: "312-68",
      careerWinPct: 82.1,
      ytdWinLoss: "48-4",
      ytdWinPct: 92.3,
      prizeMoney: "$32,800,000",
      titlesTotal: 22,
    },
    surfaces: {
      grass: {
        winPct: 68, holdPct: 76, breakPct: 38, serveRating: 72, returnRating: 80,
        tiebreakRecord: "6-8", last52: { wins: 13, losses: 6, winPct: 68 }, strength: "Strong",
      },
      clay: {
        winPct: 92, holdPct: 90, breakPct: 56, serveRating: 82, returnRating: 96,
        tiebreakRecord: "8-2", last52: { wins: 46, losses: 4, winPct: 92 }, strength: "Elite",
      },
      hard: {
        winPct: 78, holdPct: 82, breakPct: 44, serveRating: 80, returnRating: 88,
        tiebreakRecord: "10-8", last52: { wins: 39, losses: 11, winPct: 78 }, strength: "Elite",
      },
      indoor: {
        winPct: 80, holdPct: 84, breakPct: 42, serveRating: 78, returnRating: 86,
        tiebreakRecord: "5-4", last52: { wins: 16, losses: 4, winPct: 80 }, strength: "Elite",
      },
    },
    bestSurface: "Clay",
    recentMatches: [
      { opponent: "Aryna Sabalenka",     surface: "Clay",  result: "win",  score: "6-2 6-1",       tournament: "Roland Garros F",    date: "Jun 7, 2026" },
      { opponent: "Coco Gauff",          surface: "Clay",  result: "win",  score: "6-3 6-4",       tournament: "Roland Garros SF",   date: "Jun 5, 2026" },
      { opponent: "Anna Blinkova",       surface: "Clay",  result: "win",  score: "6-4 7-5",       tournament: "Roland Garros QF",   date: "Jun 3, 2026" },
      { opponent: "Elena Rybakina",      surface: "Clay",  result: "win",  score: "6-0 6-3",       tournament: "Rome F",             date: "May 18, 2026" },
      { opponent: "Jessica Pegula",      surface: "Clay",  result: "win",  score: "6-2 6-2",       tournament: "Rome SF",            date: "May 16, 2026" },
      { opponent: "Marketa Vondrousova", surface: "Clay",  result: "win",  score: "6-3 6-1",       tournament: "Madrid F",           date: "May 10, 2026" },
      { opponent: "Aryna Sabalenka",     surface: "Clay",  result: "win",  score: "7-5 6-4",       tournament: "Madrid SF",          date: "May 8, 2026" },
      { opponent: "Coco Gauff",          surface: "Hard",  result: "loss", score: "3-6 6-4 6-7",   tournament: "Indian Wells F",     date: "Mar 15, 2026" },
      { opponent: "Elena Rybakina",      surface: "Hard",  result: "win",  score: "6-3 7-6",       tournament: "Indian Wells SF",    date: "Mar 13, 2026" },
      { opponent: "Maria Sakkari",       surface: "Hard",  result: "win",  score: "6-1 6-3",       tournament: "Dubai F",            date: "Feb 22, 2026" },
    ],
    serve: {
      firstServePct:        { value: 65, tourAvg: 60, explanation: "Above average consistency. She prioritizes placement over raw power." },
      firstServeWonPct:     { value: 68, tourAvg: 65, explanation: "Solid first-serve point winning. Her placement and spin make her serve effective." },
      secondServeWonPct:    { value: 52, tourAvg: 50, explanation: "Good second serve. Heavy topspin makes it hard to attack." },
      acesPct:              { value: 3.5, tourAvg: 5.0, explanation: "Below average aces. Her serve is effective through spin and placement, not power." },
      doubleFaultsPct:      { value: 3.2, tourAvg: 4.5, explanation: "Excellent control. She almost never gives away free points on serve." },
      breakPointsSavedPct:  { value: 64, tourAvg: 60, explanation: "Strong under pressure on serve. She raises her level when facing break points." },
    },
    returnAnalytics: {
      returnPointsWon: { value: 48, tourAvg: 40, explanation: "Best return game in women's tennis. She reads serves incredibly well and attacks early." },
      breakConversion:  { value: 52, tourAvg: 42, explanation: "Elite break conversion. When she earns a break point, she almost always takes it." },
      returnGamesWon:   { value: 36, tourAvg: 25, explanation: "Breaks serve at a historically dominant rate. Opponents can't hold serve against her." },
    },
    strengthMeter: { serve: 84, return: 92, consistency: 94, pressurePoints: 86, surfaceAdaptability: 78 },
    aiSummary: "Iga Świątek is the most dominant clay-court player in women's tennis history and has solidified her position as the overall #1. Her return game is the best in the sport — she breaks opponents at will with a 52% conversion rate. On clay, she's virtually unbeatable with a 92% win rate, but grass remains her weaker surface where aggressive servers can neutralize her return advantage. Her consistency (94 rating) is extraordinary — she almost never beats herself, making opponents earn every point. The biggest area for improvement is her tiebreak record, which is below expectations for a #1 player.",
    predictions: {
      "Aryna Sabalenka":  { winChance: 68, confidence: "High",   surface: "Clay", reasoning: "Świątek dominates 7-3 in H2H. Her return neutralizes Sabalenka's power. On hard courts, it's closer (55-45)." },
      "Anna Blinkova":    { winChance: 72, confidence: "Medium", surface: "Hard", reasoning: "Świątek's return handles Blinkova's serve well. Blinkova's best chance is on a fast hard court." },
      "Carlos Alcaraz":   { winChance: 5,  confidence: "High",   surface: "Any",  reasoning: "Cross-gender comparison. Alcaraz's physical advantages are overwhelming." },
      "Coco Gauff":       { winChance: 62, confidence: "Medium", surface: "Clay", reasoning: "Świątek leads H2H 8-2. On hard courts, Gauff has closed the gap significantly." },
      "Elena Rybakina":   { winChance: 60, confidence: "Medium", surface: "Clay", reasoning: "Rybakina's serve is a weapon, but Świątek's return and consistency prevail on most surfaces." },
      "Jannik Sinner":    { winChance: 5,  confidence: "High",   surface: "Any",  reasoning: "Cross-gender comparison. Physical differences make this non-competitive." },
    },
  },

  "Jannik Sinner": {
    overview: {
      name: "Jannik Sinner",
      age: 24,
      nationality: "Italy",
      flag: "🇮🇹",
      handedness: "Right-Handed",
      backhand: "Two-Handed",
      height: "6'2\" (188 cm)",
      coach: "Darren Cahill & Simone Vagnozzi",
      currentRank: 1,
      peakRank: 1,
      elo: 2190,
      recentForm: ["L","W","W","W","W","W","W","W","W","W"],
      careerWinLoss: "262-60",
      careerWinPct: 81.4,
      ytdWinLoss: "47-4",
      ytdWinPct: 92.2,
      prizeMoney: "$30,200,000",
      titlesTotal: 18,
    },
    surfaces: {
      grass: {
        winPct: 78, holdPct: 88, breakPct: 36, serveRating: 86, returnRating: 84,
        tiebreakRecord: "12-4", last52: { wins: 14, losses: 4, winPct: 78 }, strength: "Elite",
      },
      clay: {
        winPct: 75, holdPct: 82, breakPct: 40, serveRating: 80, returnRating: 82,
        tiebreakRecord: "8-5", last52: { wins: 27, losses: 9, winPct: 75 }, strength: "Strong",
      },
      hard: {
        winPct: 88, holdPct: 92, breakPct: 44, serveRating: 92, returnRating: 90,
        tiebreakRecord: "20-5", last52: { wins: 53, losses: 7, winPct: 88 }, strength: "Elite",
      },
      indoor: {
        winPct: 85, holdPct: 90, breakPct: 42, serveRating: 90, returnRating: 88,
        tiebreakRecord: "10-3", last52: { wins: 17, losses: 3, winPct: 85 }, strength: "Elite",
      },
    },
    bestSurface: "Hard Court",
    recentMatches: [
      { opponent: "Carlos Alcaraz",    surface: "Clay",  result: "loss", score: "3-6 6-2 3-6 4-6", tournament: "Roland Garros F",   date: "Jun 8, 2026" },
      { opponent: "Daniil Medvedev",   surface: "Clay",  result: "win",  score: "6-2 6-4 7-5",     tournament: "Roland Garros SF",  date: "Jun 6, 2026" },
      { opponent: "Alexander Zverev",  surface: "Clay",  result: "win",  score: "6-3 7-6 6-4",     tournament: "Roland Garros QF",  date: "Jun 4, 2026" },
      { opponent: "Taylor Fritz",      surface: "Clay",  result: "win",  score: "6-4 6-3",         tournament: "Rome SF",           date: "May 17, 2026" },
      { opponent: "Holger Rune",       surface: "Clay",  result: "win",  score: "6-1 7-5",         tournament: "Rome QF",           date: "May 15, 2026" },
      { opponent: "Novak Djokovic",    surface: "Clay",  result: "win",  score: "7-6 6-4",         tournament: "Madrid QF",         date: "May 7, 2026" },
      { opponent: "Stefanos Tsitsipas",surface: "Hard",  result: "win",  score: "6-3 6-2",         tournament: "Miami F",           date: "Mar 30, 2026" },
      { opponent: "Andrey Rublev",     surface: "Hard",  result: "win",  score: "6-1 6-2",         tournament: "Indian Wells F",    date: "Mar 16, 2026" },
      { opponent: "Ben Shelton",       surface: "Hard",  result: "win",  score: "7-5 6-3",         tournament: "Indian Wells SF",   date: "Mar 14, 2026" },
      { opponent: "Alex de Minaur",    surface: "Hard",  result: "win",  score: "6-3 6-4 6-2",     tournament: "Australian Open F", date: "Jan 26, 2026" },
    ],
    serve: {
      firstServePct:        { value: 66, tourAvg: 62, explanation: "Above average consistency. Sinner's serve has become more reliable and is now a genuine weapon." },
      firstServeWonPct:     { value: 76, tourAvg: 70, explanation: "Very strong first-serve point winning. His serve placement opens up the court." },
      secondServeWonPct:    { value: 55, tourAvg: 50, explanation: "Elite second serve. His heavy kick serve gives opponents trouble consistently." },
      acesPct:              { value: 9.0, tourAvg: 7.0, explanation: "Above average aces. His serve has evolved into a complete weapon." },
      doubleFaultsPct:      { value: 3.2, tourAvg: 4.5, explanation: "Excellent control. Among the lowest double fault rates on tour." },
      breakPointsSavedPct:  { value: 70, tourAvg: 60, explanation: "Elite under pressure. His ability to raise his level at break points is his defining trait." },
    },
    returnAnalytics: {
      returnPointsWon: { value: 46, tourAvg: 38, explanation: "Top-tier return game. He stands close and takes time away from servers." },
      breakConversion:  { value: 44, tourAvg: 40, explanation: "Very efficient at converting break points. Clinical when opportunities arise." },
      returnGamesWon:   { value: 30, tourAvg: 24, explanation: "Among the highest on tour. His return positioning and timing are world-class." },
    },
    strengthMeter: { serve: 89, return: 90, consistency: 92, pressurePoints: 92, surfaceAdaptability: 85 },
    aiSummary: "Jannik Sinner is the world #1 and the most consistent player in men's tennis. His 2026 hard-court season was historically dominant — he won the Australian Open, Indian Wells, and Miami without dropping a set. His precision ball-striking and tactical IQ are unmatched, producing the fewest unforced errors among the top 5. His pressure performance rating (92) is the highest on tour, and his tiebreak record (20-5 on hard courts) reflects supernatural clutch ability. The main vulnerability is against Alcaraz's variety on clay, where Sinner's more linear game can be disrupted by drop shots and angles.",
    predictions: {
      "Carlos Alcaraz":   { winChance: 38, confidence: "High",   surface: "Hard", reasoning: "Sinner trails 4-6 in H2H. On hard courts he's closer (3-3), but Alcaraz's variety is problematic." },
      "Iga Swiatek":      { winChance: 95, confidence: "High",   surface: "Any",  reasoning: "Cross-gender comparison. Physical advantages are decisive." },
      "Anna Blinkova":    { winChance: 85, confidence: "High",   surface: "Hard", reasoning: "Sinner's consistency and pressure performance are overwhelming against mid-ranked opponents." },
      "Novak Djokovic":   { winChance: 70, confidence: "Medium", surface: "Hard", reasoning: "Sinner has won 5 of last 6 meetings. Djokovic's movement decline is exploited by Sinner's heavy hitting." },
      "Daniil Medvedev":  { winChance: 72, confidence: "High",   surface: "Hard", reasoning: "Sinner dominates this rivalry 8-3. Medvedev's defense can't handle Sinner's power and consistency." },
      "Alexander Zverev": { winChance: 75, confidence: "High",   surface: "Any",  reasoning: "Sinner is too consistent for Zverev. Only Zverev's serve keeps him in rallies." },
    },
  },
};
